spring:
  datasource:
    url: jdbc:mysql://b21b5931cc8989:b1fb5fbf@us-cdbr-east-05.cleardb.net/heroku_83e65bacf3b9653?reconnect=true
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    org:
      hibernate:
        SQL: debug
